[package]

name = "resonance"
version = "0.0.1"
authors = ["Ben Williamson <benw@pobox.com>"]

[dependencies.openal-rs]

#git = "https://github.com/bjz/openal-rs.git"
git = "file:///Users/benw/src/rust/openal-rs"

